<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <Version>0.1.1</Version>
    <AssemblyVersion>0.1.1.0</AssemblyVersion>
    <FileVersion>0.1.1.0</FileVersion>
    <InformationalVersion>0.1.1</InformationalVersion>
    <DefaultLanguage>zh-CN</DefaultLanguage>
    <AppxBundleAutoResourcePackageQualifiers>Scale|DXFeatureLevel</AppxBundleAutoResourcePackageQualifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\external\SpatialViewer.CadCore\src\SpatialViewer.Core\SpatialViewer.Core.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=$(Platform)" />
    <ProjectReference Include="..\..\external\SpatialViewer.CadCore\src\SpatialViewer.Rendering\SpatialViewer.Rendering.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=$(Platform)" />
    <ProjectReference Include="..\..\external\SpatialViewer.CadCore\src\SpatialViewer.Rendering.Windows\SpatialViewer.Rendering.Windows.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=$(Platform)" />
    <ProjectReference Include="..\..\external\SpatialViewer.CadCore\src\SpatialViewer.Formats.Cad\SpatialViewer.Formats.Cad.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=$(Platform)" />
    <ProjectReference Include="..\..\external\SpatialViewer.CadCore\src\SpatialViewer.Formats.Cad.ACadSharp\SpatialViewer.Formats.Cad.ACadSharp.csproj" SetConfiguration="Configuration=$(Configuration)" SetPlatform="Platform=$(Platform)" />
    <ProjectReference Include="..\SpatialViewer.Presentation\SpatialViewer.Presentation.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260710003" />
  </ItemGroup>
</Project>
